# Generated by Django 4.0.4 on 2022-04-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(max_length=255)),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
                ('positive_votes', models.IntegerField(default=0)),
                ('negative_votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='ContentVote',
        ),
    ]
